3.1 Array Introduction:
1. Importing Numpy:
Sample Code from Slide - 14 - Importing Numpy and Array Type

In [ ]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



2. Array Dimensions: Shape and Resahpe of Array:
Sample Code from Slide - 16 - Shape of an Array.


In [ ]:
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")


0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



Sample Code from Slide - 17 - Reshaping an Array.


In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


3.2 Array Creation:
1. Using In - Built Function:
Sample Code from Slide - 18 - Arrays with evenly Spaced values - arange

In [ ]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)


[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


Sample Code from Slide - 19 - Arrays with evenly Spaced values - linspace.


In [ ]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


2. Initializing Arrays with Ones, Zeros and Empty:
Sample Code form slide - 20 - Initializing an Array.

In [ ]:
import numpy as np

# Create arrays of specified shapes
ones_array = np.ones((2, 3))  # Shape: (2, 3)
zeros_array = np.zeros((3, 2))  # Shape: (3, 2)
empty_array = np.empty((2, 2))  # Shape: (2, 2)
identity_matrix = np.eye(3)  # Shape: (3, 3)

# Print arrays with proper formatting for newline
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')


[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.87414994e-310 0.00000000e+000]
 [2.05833592e-312 6.63743532e-310]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. By Manipulating Existing Array:
3.1 Using np.array:
Sample Code form slide - 21 - Converting list to array using np.array.

In [ ]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n\n')


[1 2 3]

[4 5 6]

[[1 2 3]
 [4 5 6]]


3.2 Using shape of an existing array:
Sample Code form slide - 22 - From shape of an existing array.

In [ ]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[4.87414985e-310 0.00000000e+000 6.63743588e-310]
 [6.63743588e-310 6.63743588e-310 6.63743588e-310]]


3.3 With Math, Copying or Slicing and Array:
Sample Code form slide - 23 - Manipulatiing existing array

In [ ]:
import numpy as np
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np.copy(array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]


Sample Code form slide - 26 - With Concatenating Operation.


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n\n')


[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


3.4 Array: Indexing and Slicing:
Sample Code form slide - 34 - Sample Code for Indexing and Slicing

In [ ]:
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]


Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


3.3 Array Mathematics:
1. Elementary Mathematical Operation with universal functions.
Sample Code form slide - 37 - Intriduction to ”ufuncs”.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2))
print("Subtract:", np.subtract(arr1, arr2))
print("Divide:", np.divide(arr1, arr2))
print("Multiply:", np.multiply(arr1, arr2))
print("Power:", np.power(arr1, arr2))
print("Exp:", np.exp(arr1))

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


2. Matrix Multiplications.
Sample Code form slide - 44 - Using ”np.dot”.

In [ ]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


Sample Code form slide - 45 - Using ”np.matmul”.


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
result_at = A @ B
print("Result with @ operator:\n", result_at)
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul)


Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


3.4 Linear Algebra with Numpy - np.linalg:
Sample Code form slide - 48 - Common linear algebra operation with np.linalg.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))

print("Determinant:", np.linalg.det(A))

print("Frobenius Norm:", np.linalg.norm(A, 'fro'))

print("2-Norm (Euclidean):", np.linalg.norm(A))

print("Solution x:", np.linalg.solve(A, B))


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
arr=np.empty((2,2))
print(arr)

arr1=np.ones((4,2))
print(arr1)

arr2=np.full((4,2),1)
print(arr2)

arr3=np.zeros_like(arr2)
print(arr3)

arr4=np.ones_like(arr2)
print(arr4)

new_list=[1,2,3,4]
arr5=np.array(new_list)
print(arr5)


[[1. 2.]
 [3. 4.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[1 2 3 4]


 4.1 WarmingUpExercise: Basic Vector and Matrix Operation with Numpy.
 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7
shape = (3, 3)
filled_array = np.full(shape, fill_value)
print("\nArray Filled with Value 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
example_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(example_array)
print("\nZeros Array with Same Shape as example_array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nOnes Array with Same Shape as example_array:\n", ones_like_array)

# 6. Convert the list `new_list = [1, 2, 3, 4]` to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy Array from List:\n", numpy_array)


Empty Array (2x2):
 [[4.93123385e-310 0.00000000e+000]
 [            nan 2.84347436e-311]]

All-Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with Value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as example_array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as example_array:
 [[1 1 1]
 [1 1 1]]

Numpy Array from List:
 [1 2 3 4]



 4.1.1 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [4]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", array_range)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values ranging from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the random array:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Array with Random Values:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element Replaced by 1:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.83480997 0.36519187 0.59633118 0.66586558 0.19488279 0.14764921
 0.21190485 0.45699445 0.05615723 0.70938032 0.49084266 0.77529569
 0.64508623 0.72016194 0.36154863 0.07276973 0.35906659 0.6059452
 0.73052716 0.26412528 0.36287536 0.13993254 0.03295586 0.0594192
 0.4992877  0.44054942 0.94437003 0.31148647 0.97025887 0.14939325]
Mean of the random array: 0.43916884128256656

10x10 Array with Random Values:
 [[0.67355166 0.98989622 0.87951213 0.38573402 0.26112459 0.64030108
  0.87143519 0.74916744 0.53673368 0.45972565]
 [0.0609093  0.23858065 0.34906739 0.14977105 0.72083853 0.17227614
  0.63933523 0.37771434 0.46018246 0.88145723]
 [0.20274801 0.94501158 0.0387

 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error

In [3]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x and y)
add_result = x + y
print("Addition of x and y:\n", add_result)

# 2. Subtract the two arrays (x and y)
subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

# 3. Multiply the array x with an integer (e.g., 3)
scalar_multiplication = x * 3
print("\nMultiplication of x with 3:\n", scalar_multiplication)

# 4. Find the square of each element in the array x
square_result = x ** 2
print("\nSquare of each element in x:\n", square_result)

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot Product of v and w:", dot_vw)
print("Dot Product of x and v:\n", dot_xv)
print("Dot Product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows; Concatenate v and w along columns
concatenate_xy = np.concatenate((x, y), axis=0)
concatenate_vw = np.vstack((v, w))
print("\nConcatenation of x and y along rows:\n", concatenate_xy)
print("Concatenation of v and w along columns:\n", concatenate_vw)

# 7. Concatenate x and v
try:
    concatenate_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concatenate_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot Product of v and w: 219
Dot Product of x and v:
 [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}


In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
identity_matrix_rounded = np.round(identity_matrix)
print("A * A^-1 = Identity Matrix:\n", identity_matrix_rounded)

# 2. Prove AB = BA
AB = np.dot(A, B)
BA = np.dot(B, A)
is_commutative = np.array_equal(AB, BA)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nIs AB equal to BA? ", is_commutative)

# 3. Prove (AB)T = BTAT
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
is_transpose_property = np.array_equal(AB_T, BT_AT)
print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)
print("\nIs (AB)^T equal to B^T * A^T? ", is_transpose_property)

coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
rhs_matrix = np.array([-1, -3, 9])  #

# Solve using `np.linalg.inv`
A_inv_3x3 = np.linalg.inv(coeff_matrix)
solution = np.dot(A_inv_3x3, rhs_matrix)
print("\nSolution to the system of equations using inverse method:\n", solution)

# Solve using `np.linalg.solve` (more numerically stable)
solution_linalg = np.linalg.solve(coeff_matrix, rhs_matrix)
print("\nSolution to the system of equations using `np.linalg.solve`:\n", solution_linalg)


A * A^-1 = Identity Matrix:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?  False

(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T?  True

Solution to the system of equations using inverse method:
 [ 2.  1. -2.]

Solution to the system of equations using `np.linalg.solve`:
 [ 2.  1. -2.]
